### PR TITLE
Feature comment show

### PR DESCRIPTION
**Pull request by jackschultz**

### CODE REVIEW

**Comment by bcroesch** [comment]
@jackschultz assume we still need to integrate this into forecasts? Or did you already test there?

**Comment by jackschultz** [comment]
Yeah we need to integrate it, but I didn't exactly know where. Like we talked about using it in emails or the like, but other than that not sure where.

**Comment by bcroesch** [comment]
I don't think we necessarily need to link to it anywhere yet, but testing/verifying that we can go to /comments/comments/123 or whatever and have it display the top level comment + thread in the manner we'd we be ok with using in an email link or permalink in the comment footer.

**Comment by jackschultz** [comment]
https://github.com/CultivateLabs/flyover_forecasts/pull/321

**Pull request merged**
